### ISSUE TITLE
Please make sure libcudnn_ops_infer.so.8 is in your library path

### ISSUE THREAD

**Issue by doctorhai** [alesaccoia/VoiceStreamAI#10]
Trying to run the demo and docker container but getting this error:
`Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../root/.cache/torch/pyannote/models--pyannote--segmentation/snapshots/2ffce0501d0aecad81b43a06d538186e292d0070/pytorch_model.bin`
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!`

Do you know how to resolve this?

**Comment by jinmiaoluo** [comment]
This is a good issue, we should reopen and fix it.

**Comment by jinmiaoluo** [comment]
I will create a new issue and fix it, just FYI: https://github.com/alesaccoia/VoiceStreamAI/issues/17
