### ISSUE TITLE
Transcribing fragmented audio with codec

### ISSUE THREAD

**Issue by kenho211** [alesaccoia/VoiceStreamAI#32]
Is there way to get the audio from fragmented audio, for example from MPEG-DASH / HLS stream?

**Comment by alesaccoia** [comment]
I think you'd need to put something in front of VoiceStreamAI to do that

**Comment by kenho211** [comment]
Thank you. I am able to do that by concatenating the init segment with the others, then parse them.

**Comment by alesaccoia** [comment]
@kenho211 that's a nice use case, if you wanted to contribute to the repo with a minimal demo would be welcome. cheers
